# Generated by Django 5.1.3 on 2024-11-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.clients')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.drivers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.products')),
            ],
        ),
    ]
