# Generated by Django 5.1.3 on 2024-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
