# Generated by Django 5.1.3 on 2024-12-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orders_client_alter_orders_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='driver',
        ),
    ]
