# Generated by Django 5.1.3 on 2024-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
