# Generated by Django 5.1.3 on 2024-11-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.clients'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.drivers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.products'),
        ),
    ]
