# Generated by Django 5.1.3 on 2024-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orders_client_id_alter_orders_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
    ]
