# Generated by Django 5.1.3 on 2024-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-11-22'),
            preserve_default=False,
        ),
    ]
