# Generated by Django 5.1.3 on 2024-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
