# Generated by Django 5.1.3 on 2024-11-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='order.clients', to_field='client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='driver_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='order.drivers', to_field='driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='order.products', to_field='product'),
            preserve_default=False,
        ),
    ]
